"""update habits

Revision ID: 815104a187b7
Revises: 9c1a7f9f166d
Create Date: 2026-01-31 18:04:05.596803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815104a187b7'
down_revision: Union[str, Sequence[str], None] = '9c1a7f9f166d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('step', sa.Integer(), nullable=True))
    op.drop_column('habits', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('habits', 'step')
    # ### end Alembic commands ###
